# TODO Create your inputs, variables, and add your story here!noun = input("Enter a noun: ")
noun - input("Enter a noun: ")
adjective = input("Enter an adjective: ")
verb = input ("Enter a verb: ") 
print(f"The", {noun}, "was extremely", {adjective}, "and", {verb}, "with their friends")